// Generated by https://quicktype.io

export type CategoryMock = {
  id: number;
  name: string;
  url: string;
  image: string;
};

export interface CategoriesResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: Category[];
}

export interface CategoryPutRequest {
  name: string;
  description: string;
}

export interface Category extends CategoryPutRequest {
  id: string;
  created_at: string;
  updated_at: string;
}
